# Generated by Django 4.0 on 2022-11-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=200)),
                ('stubirthday', models.DateField()),
                ('stuphoto', models.ImageField(upload_to='')),
                ('stuemail', models.EmailField(max_length=254)),
                ('stugrade', models.IntegerField()),
                ('stuclass', models.CharField(max_length=1)),
                ('sturegdate', models.DateField(auto_now=True)),
                ('stuentrance', models.IntegerField()),
                ('sturesidance', models.CharField(max_length=200)),
                ('stuguardian', models.CharField(max_length=200)),
                ('stugtele', models.IntegerField()),
                ('stugemail', models.EmailField(max_length=254)),
                ('stumother', models.CharField(max_length=200)),
                ('stumothertele', models.IntegerField()),
                ('stuotherskills', models.CharField(max_length=200)),
                ('stucertificate', models.FileField(upload_to='')),
                ('stuletter', models.FileField(upload_to='')),
                ('stumedical', models.FileField(upload_to='')),
                ('stusports', models.CharField(max_length=200)),
                ('stupassword', models.CharField(max_length=200)),
            ],
        ),
    ]
