# Generated by Django 4.0 on 2022-11-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='stuemail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
