# Generated by Django 4.0 on 2022-11-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_new_user_stuemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='sturesidance',
            field=models.TextField(),
        ),
    ]
